package exception;

public class exceptionTest {
    public static void main(String[] args) {
        /*int a, b, c;
        try {
            a = 10;
            b = 0;
            c = a / b;
        } catch (Exception e) {
            c = -1;
            System.out.println(e);
        }*/





        // printStackTrace() 를 catch 문 안에서 실행하면
        // 부모 예외 클래스로 한꺼번에 예외 상황을 받아들여도
        // 어떠한 예외 상황인지 세세하게 출력하여 추적 가능하다.
    }
}
